#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright © 2025 CCP ehf.

"""Generate ImGui-readable Font Awesome headers.

This script has two purposes:
1) Generate a font byte-data header consumable by Dear ImGui.
2) Generate a Font Awesome icon define header for use in C++ UI code.

The output style intentionally mirrors the spirit of
https://github.com/ocornut/imgui/blob/master/misc/fonts/binary_to_compressed_c.cpp
by emitting a `unsigned int` data array and explicit byte size.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


def _find_repo_root() -> Path:
	"""Resolve repository root from this script location."""
	return Path(__file__).resolve().parents[3]


def _chunked(values: Iterable[int], chunk_size: int) -> Iterable[List[int]]:
	chunk: List[int] = []
	for value in values:
		chunk.append(value)
		if len(chunk) == chunk_size:
			yield chunk
			chunk = []
	if chunk:
		yield chunk


def _bytes_to_u32_words(data: bytes) -> List[int]:
	words: List[int] = []
	for i in range(0, len(data), 4):
		block = data[i : i + 4]
		value = 0
		for byte_index, byte_value in enumerate(block):
			value |= byte_value << (byte_index * 8)
		words.append(value)
	return words


def _format_word_array(words: List[int], per_line: int = 12) -> str:
	formatted_lines: List[str] = []
	for chunk in _chunked(words, per_line):
		joined = ", ".join(f"0x{value:08x}" for value in chunk)
		formatted_lines.append(f"    {joined},")
	return "\n".join(formatted_lines)


def _sanitize_macro_suffix(icon_name: str) -> str:
	upper = icon_name.upper().replace("-", "_")
	upper = re.sub(r"[^A-Z0-9_]", "_", upper)
	upper = re.sub(r"_+", "_", upper).strip("_")
	return upper if upper else "UNKNOWN"


def _codepoint_to_utf8_hex_escapes(codepoint: int) -> str:
	encoded = chr(codepoint).encode("utf-8")
	return "".join(f"\\x{byte:02x}" for byte in encoded)


def _load_icons(icons_json_path: Path) -> List[Tuple[str, int]]:
	with icons_json_path.open("r", encoding="utf-8") as input_file:
		icon_data: Dict[str, Dict[str, object]] = json.load(input_file)

	icons: List[Tuple[str, int]] = []
	for icon_name, payload in icon_data.items():
		styles = payload.get("styles", [])
		unicode_hex = payload.get("unicode")
		if "solid" not in styles or not isinstance(unicode_hex, str):
			continue

		codepoint = int(unicode_hex, 16)
		icons.append((icon_name, codepoint))

	icons.sort(key=lambda item: item[0])
	return icons


def _build_font_header(ttf_bytes: bytes, ttf_path: Path) -> str:
	words = _bytes_to_u32_words(ttf_bytes)
	array_body = _format_word_array(words)

	return (
		"// Auto-generated by fontAwesomeCreator.py.\n"
		"// Source TTF: "
		f"{ttf_path.as_posix()}\n"
		"// Dear ImGui usage example:\n"
		"// io.Fonts->AddFontFromMemoryTTF(\n"
		"//     const_cast<unsigned int*>(fa_solid_900_ttf_data),\n"
		"//     static_cast<int>(fa_solid_900_ttf_size),\n"
		"//     16.0f, &config, iconRanges);\n"
		"#pragma once\n\n"
		"static const unsigned int fa_solid_900_ttf_size = "
		f"{len(ttf_bytes)}u;\n"
		f"static const unsigned int fa_solid_900_ttf_data[{len(words)}] =\n"
		"{\n"
		f"{array_body}\n"
		"};\n"
	)


def _build_icon_define_header(icons: List[Tuple[str, int]], icons_path: Path) -> str:
	if not icons:
		raise ValueError("No solid icons were found in the input icons metadata.")

	min_cp = min(codepoint for _, codepoint in icons)
	max_cp = max(codepoint for _, codepoint in icons)

	lines: List[str] = [
		"// Auto-generated by fontAwesomeCreator.py.",
		f"// Source icons.json: {icons_path.as_posix()}",
		"#pragma once",
		"",
		f"#define ICON_MIN_FA 0x{min_cp:04x}",
		f"#define ICON_MAX_FA 0x{max_cp:04x}",
		"",
	]

	for icon_name, codepoint in icons:
		macro_suffix = _sanitize_macro_suffix(icon_name)
		utf8_escaped = _codepoint_to_utf8_hex_escapes(codepoint)
		lines.append(f"#define ICON_FA_{macro_suffix} \"{utf8_escaped}\"")

	lines.append("")
	return "\n".join(lines)


def _parse_args(argv: List[str]) -> Tuple[Path, Path, Path, Path]:
	"""
	Supported forms:
	- fontAwesomeCreator.py <input_ttf> <icons_json> <out_font_header> <out_define_header>
	"""
	if len(argv) == 5:
		input_ttf = Path(argv[1]).resolve()
		icons_json = Path(argv[2]).resolve()
		output_font_header = Path(argv[3]).resolve()
		output_define_header = Path(argv[4]).resolve()
		return input_ttf, icons_json, output_font_header, output_define_header

	usage = (
		"Usage:\n"
		"  python fontAwesomeCreator.py <out_font_header> <out_define_header>\n"
		"  python fontAwesomeCreator.py <icons_json> <out_font_header> <out_define_header>\n"
		"  python fontAwesomeCreator.py <input_ttf> <icons_json> <out_font_header> <out_define_header>"
	)
	raise ValueError(usage)


def main(argv: List[str]) -> int:
	try:
		input_ttf, icons_json, out_font_header, out_define_header = _parse_args(argv)

		if not input_ttf.is_file():
			raise FileNotFoundError(f"Input TTF not found: {input_ttf}")
		if not icons_json.is_file():
			raise FileNotFoundError(f"Input icons JSON not found: {icons_json}")

		out_font_header.parent.mkdir(parents=True, exist_ok=True)
		out_define_header.parent.mkdir(parents=True, exist_ok=True)

		ttf_bytes = input_ttf.read_bytes()
		icons = _load_icons(icons_json)

		out_font_header.write_text(_build_font_header(ttf_bytes, input_ttf), encoding="utf-8")
		out_define_header.write_text(_build_icon_define_header(icons, icons_json), encoding="utf-8")
	except Exception as exc:  # broad catch to keep the generator easy to diagnose from CMake logs
		print(str(exc))
		return 1

	return 0


if __name__ == "__main__":
	sys.exit(main(sys.argv))
